### ISSUE TITLE
timeout.tv_nsec is set incorrectly in Linux version

### ISSUE THREAD

**Issue by stravager** [tesseract241/lockless_sleep_and_wake#1]
`timeout.tv_nsec = (timeout_milliseconds % 1000) * 1000;`

missing a few zeroes at the end there there to give **n**ano**sec**onds.

**Comment by tesseract241** [comment]
Should be fixed in a6a0102, will close this issue tomorrow if this is satisfactory.

**Comment by tesseract241** [comment]
Solved in a6a0102
